### ISSUE TITLE
Thư ngỏ

### ISSUE THREAD

**Issue by buukhanh243** [vutienhung260798/text-summarization#1]
Chào anh! anh còn giữ báo cáo bài viết này không ạ. Cho em xin với ạ. Em xin cảm ơn mã nguồn bổ ích của a
buukhanh243@gmail.com

**Comment by vutienhung260798** [comment]
Ok em!! Cứ lấy thôi em nhé :))))
  
  
  
    
  

  
  
>

**Comment by buukhanh243** [comment]
Nếu anh còn giữ file word của bài cho em xin mượn đọc thêm về cái cluster với ạ, em xin cảm ơn a nhé

**Comment by vutienhung260798** [comment]
Em lên mạng search machine learning cơ bản là có đó em   
  
  
  
    
  

  
  
>
